name: DAST Scan

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run ZAP OWASP full scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          token: ${{ secrets.MY_SECRET_KEY }}
          target: 'http://localhost:8080' # Adjust the target URL

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: DAST_Report
          path: C:\Users\Dell\Downloads\OWASP_ZAP\report.html.txt # Path to the ZAP HTML report
