name: Wapiti DAST Scan

on:
  push:
    branches:
      - main

jobs:
  wapiti-scan:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Reports Directory
        run: mkdir -p ./reports

      - name: Run Wapiti Scan
        run: |
          ./wapiti ./Users/Dell/OneDrive/Documents/Github -o ./reports/report.html
