name: Push to Another Repository

on:
  push:
    branches:
      - main

jobs:
  push_code:
    runs-on: windows-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Push to Target Repository
        run: |
          REM Set up Git user
          git config --global user.name "shashankhegde06"
          git config --global user.email "eng21ct0036@dsu.edu.in"

          REM Add the target repository as a remote
          git remote add target-repo https://github.com/shashankhegde06/shashankhegde06.git

          REM Push the code to the target repository
          git push target-repo main:main

        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_KEY }}
